#!/bin/bash

./ecl2lsg.cpp.exe graphs/2d-2e20.sym.egr 2d-2e20.sym.ls
echo " "
./ecl2lsg.cpp.exe graphs/amazon0601.egr amazon0601.ls
echo " "
./ecl2lsg.cpp.exe graphs/as-skitter.egr as-skitter.ls
echo " "
./ecl2lsg.cpp.exe graphs/citationCiteseer.egr citationCiteseer.ls
echo " "
./ecl2lsg.cpp.exe graphs/cit-Patents.egr cit-Patents.ls
echo " "
./ecl2lsg.cpp.exe graphs/coPapersDBLP.egr coPapersDBLP.ls
echo " "
./ecl2lsg.cpp.exe graphs/delaunay_n24.egr delaunay_n24.ls
echo " "
./ecl2lsg.cpp.exe graphs/europe_osm.egr europe_osm.ls
echo " "
./ecl2lsg.cpp.exe graphs/in-2004.egr in-2004.ls
echo " "
./ecl2lsg.cpp.exe graphs/internet.egr internet.ls
echo " "
./ecl2lsg.cpp.exe graphs/kron_g500-logn21.egr kron_g500-logn21.ls
echo " "
./ecl2lsg.cpp.exe graphs/r4-2e23.sym.egr r4-2e23.sym.ls
echo " "
./ecl2lsg.cpp.exe graphs/rmat16.sym.egr rmat16.sym.ls
echo " "
./ecl2lsg.cpp.exe graphs/rmat22.sym.egr rmat22.sym.ls
echo " "
./ecl2lsg.cpp.exe graphs/soc-LiveJournal1.egr soc-LiveJournal1.ls
echo " "
./ecl2lsg.cpp.exe graphs/uk-2002.egr uk-2002.ls
echo " "
./ecl2lsg.cpp.exe graphs/USA-road-d.NY.egr USA-road-d.NY.ls
echo " "
./ecl2lsg.cpp.exe graphs/USA-road-d.USA.egr USA-road-d.USA.ls
echo " "
