
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-29T17:12:09-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "5c6bf51f44b54f0e77afd60da2a038b58f4d515f",
 "version": "23.02.00a+68.g5c6bf51f.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
